// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53YoApvcFSOYpoC3SBEVFI05fh5-6tf0',
    appId: '1:1067350563771:web:cb3ea32cd4a8433a50429e',
    messagingSenderId: '1067350563771',
    projectId: 'admission-app-eaef0',
    authDomain: 'admission-app-eaef0.firebaseapp.com',
    storageBucket: 'admission-app-eaef0.firebasestorage.app',
    measurementId: 'G-5R5PP2Z4ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRKRnxGQltgZkyHoCQ8-jAllPou8wtdCo',
    appId: '1:1067350563771:android:706a854bab503dca50429e',
    messagingSenderId: '1067350563771',
    projectId: 'admission-app-eaef0',
    storageBucket: 'admission-app-eaef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnz40r0JXbQVm63LCMhZEUr3si4MjgDY',
    appId: '1:1067350563771:ios:a5b9c66d1f1f049050429e',
    messagingSenderId: '1067350563771',
    projectId: 'admission-app-eaef0',
    storageBucket: 'admission-app-eaef0.firebasestorage.app',
    iosBundleId: 'com.example.admissionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLnz40r0JXbQVm63LCMhZEUr3si4MjgDY',
    appId: '1:1067350563771:ios:a5b9c66d1f1f049050429e',
    messagingSenderId: '1067350563771',
    projectId: 'admission-app-eaef0',
    storageBucket: 'admission-app-eaef0.firebasestorage.app',
    iosBundleId: 'com.example.admissionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD53YoApvcFSOYpoC3SBEVFI05fh5-6tf0',
    appId: '1:1067350563771:web:6c5b5322c260163a50429e',
    messagingSenderId: '1067350563771',
    projectId: 'admission-app-eaef0',
    authDomain: 'admission-app-eaef0.firebaseapp.com',
    storageBucket: 'admission-app-eaef0.firebasestorage.app',
    measurementId: 'G-XYS9G8X58X',
  );
}
